/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as EventosCorporativosRouteImport } from './routes/eventos-corporativos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FotoProfissionalRouteImport } from './routes/foto-profissional'
import { Route as FotoProfissionalParaLinkedinRouteImport } from './routes/foto-profissional-para-linkedin'
import { Route as FotografiaExecutivaRouteImport } from './routes/fotografia-executiva'
import { Route as FotografiaParaAdvogadosRouteImport } from './routes/fotografia-para-advogados'
import { Route as FotografiaParaClinicasRouteImport } from './routes/fotografia-para-clinicas'
import { Route as FotografoDeFeiraDeNegociosRouteImport } from './routes/fotografo-de-feira-de-negocios'
import { Route as FotografoEmpresarialRouteImport } from './routes/fotografo-empresarial'
import { Route as FotosCorporativasRouteImport } from './routes/fotos-corporativas'
import { Route as FotosProfissionaisMedicosRouteImport } from './routes/fotos-profissionais-medicos'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as QuemEOAleRouteImport } from './routes/quem-e-o-ale'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapVideosDotxmlRouteImport } from './routes/sitemap-videos[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as VideoDeEventosCorporativosRouteImport } from './routes/video-de-eventos-corporativos'
import { Route as VideoInstitucionalRouteImport } from './routes/video-institucional'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as FotografoCorporativoEmIndexRouteImport } from './routes/fotografo-corporativo-em.index'
import { Route as FotografoCorporativoEmBairroRouteImport } from './routes/fotografo-corporativo-em.$bairro'
import { Route as FotografoCorporativoIndexRouteImport } from './routes/fotografo-corporativo.index'
import { Route as FotografoCorporativoSlugRouteImport } from './routes/fotografo-corporativo.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as AuthenticatedAdminDesempenhoRouteImport } from './routes/_authenticated/admin.desempenho'
import { Route as AuthenticatedAdminIndexacaoRouteImport } from './routes/_authenticated/admin.indexacao'
import { Route as AuthenticatedAdminMonitoramentoRouteImport } from './routes/_authenticated/admin.monitoramento'
import { Route as ApiPublicCronIndexingRouteImport } from './routes/api/public/cron-indexing'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'
import { Route as ApiPublicStaticmapRouteImport } from './routes/api/public/staticmap'
import { Route as FotografoCorporativoCategoriaSlugRouteImport } from './routes/fotografo-corporativo.categoria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosCorporativosRoute = EventosCorporativosRouteImport.update({
  id: '/eventos-corporativos',
  path: '/eventos-corporativos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoProfissionalRoute = FotoProfissionalRouteImport.update({
  id: '/foto-profissional',
  path: '/foto-profissional',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoProfissionalParaLinkedinRoute =
  FotoProfissionalParaLinkedinRouteImport.update({
    id: '/foto-profissional-para-linkedin',
    path: '/foto-profissional-para-linkedin',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografiaExecutivaRoute = FotografiaExecutivaRouteImport.update({
  id: '/fotografia-executiva',
  path: '/fotografia-executiva',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografiaParaAdvogadosRoute = FotografiaParaAdvogadosRouteImport.update({
  id: '/fotografia-para-advogados',
  path: '/fotografia-para-advogados',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografiaParaClinicasRoute = FotografiaParaClinicasRouteImport.update({
  id: '/fotografia-para-clinicas',
  path: '/fotografia-para-clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografoDeFeiraDeNegociosRoute =
  FotografoDeFeiraDeNegociosRouteImport.update({
    id: '/fotografo-de-feira-de-negocios',
    path: '/fotografo-de-feira-de-negocios',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografoEmpresarialRoute = FotografoEmpresarialRouteImport.update({
  id: '/fotografo-empresarial',
  path: '/fotografo-empresarial',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosCorporativasRoute = FotosCorporativasRouteImport.update({
  id: '/fotos-corporativas',
  path: '/fotos-corporativas',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosProfissionaisMedicosRoute =
  FotosProfissionaisMedicosRouteImport.update({
    id: '/fotos-profissionais-medicos',
    path: '/fotos-profissionais-medicos',
    getParentRoute: () => rootRouteImport,
  } as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemEOAleRoute = QuemEOAleRouteImport.update({
  id: '/quem-e-o-ale',
  path: '/quem-e-o-ale',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapVideosDotxmlRoute = SitemapVideosDotxmlRouteImport.update({
  id: '/sitemap-videos.xml',
  path: '/sitemap-videos.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoDeEventosCorporativosRoute =
  VideoDeEventosCorporativosRouteImport.update({
    id: '/video-de-eventos-corporativos',
    path: '/video-de-eventos-corporativos',
    getParentRoute: () => rootRouteImport,
  } as any)
const VideoInstitucionalRoute = VideoInstitucionalRouteImport.update({
  id: '/video-institucional',
  path: '/video-institucional',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografoCorporativoEmIndexRoute =
  FotografoCorporativoEmIndexRouteImport.update({
    id: '/fotografo-corporativo-em/',
    path: '/fotografo-corporativo-em/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografoCorporativoEmBairroRoute =
  FotografoCorporativoEmBairroRouteImport.update({
    id: '/fotografo-corporativo-em/$bairro',
    path: '/fotografo-corporativo-em/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografoCorporativoIndexRoute =
  FotografoCorporativoIndexRouteImport.update({
    id: '/fotografo-corporativo/',
    path: '/fotografo-corporativo/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografoCorporativoSlugRoute =
  FotografoCorporativoSlugRouteImport.update({
    id: '/fotografo-corporativo/$slug',
    path: '/fotografo-corporativo/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDesempenhoRoute =
  AuthenticatedAdminDesempenhoRouteImport.update({
    id: '/admin/desempenho',
    path: '/admin/desempenho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexacaoRoute =
  AuthenticatedAdminIndexacaoRouteImport.update({
    id: '/admin/indexacao',
    path: '/admin/indexacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMonitoramentoRoute =
  AuthenticatedAdminMonitoramentoRouteImport.update({
    id: '/admin/monitoramento',
    path: '/admin/monitoramento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronIndexingRoute = ApiPublicCronIndexingRouteImport.update({
  id: '/api/public/cron-indexing',
  path: '/api/public/cron-indexing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStaticmapRoute = ApiPublicStaticmapRouteImport.update({
  id: '/api/public/staticmap',
  path: '/api/public/staticmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografoCorporativoCategoriaSlugRoute =
  FotografoCorporativoCategoriaSlugRouteImport.update({
    id: '/fotografo-corporativo/categoria/$slug',
    path: '/fotografo-corporativo/categoria/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/eventos-corporativos': typeof EventosCorporativosRoute
  '/faq': typeof FaqRoute
  '/foto-profissional': typeof FotoProfissionalRoute
  '/foto-profissional-para-linkedin': typeof FotoProfissionalParaLinkedinRoute
  '/fotografia-executiva': typeof FotografiaExecutivaRoute
  '/fotografia-para-advogados': typeof FotografiaParaAdvogadosRoute
  '/fotografia-para-clinicas': typeof FotografiaParaClinicasRoute
  '/fotografo-de-feira-de-negocios': typeof FotografoDeFeiraDeNegociosRoute
  '/fotografo-empresarial': typeof FotografoEmpresarialRoute
  '/fotos-corporativas': typeof FotosCorporativasRoute
  '/fotos-profissionais-medicos': typeof FotosProfissionaisMedicosRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/quem-e-o-ale': typeof QuemEOAleRoute
  '/servicos': typeof ServicosRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/video-de-eventos-corporativos': typeof VideoDeEventosCorporativosRoute
  '/video-institucional': typeof VideoInstitucionalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/fotografo-corporativo-em/$bairro': typeof FotografoCorporativoEmBairroRoute
  '/fotografo-corporativo/$slug': typeof FotografoCorporativoSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/fotografo-corporativo-em/': typeof FotografoCorporativoEmIndexRoute
  '/fotografo-corporativo/': typeof FotografoCorporativoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/admin/desempenho': typeof AuthenticatedAdminDesempenhoRoute
  '/admin/indexacao': typeof AuthenticatedAdminIndexacaoRoute
  '/admin/monitoramento': typeof AuthenticatedAdminMonitoramentoRoute
  '/api/public/cron-indexing': typeof ApiPublicCronIndexingRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/staticmap': typeof ApiPublicStaticmapRoute
  '/fotografo-corporativo/categoria/$slug': typeof FotografoCorporativoCategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/eventos-corporativos': typeof EventosCorporativosRoute
  '/faq': typeof FaqRoute
  '/foto-profissional': typeof FotoProfissionalRoute
  '/foto-profissional-para-linkedin': typeof FotoProfissionalParaLinkedinRoute
  '/fotografia-executiva': typeof FotografiaExecutivaRoute
  '/fotografia-para-advogados': typeof FotografiaParaAdvogadosRoute
  '/fotografia-para-clinicas': typeof FotografiaParaClinicasRoute
  '/fotografo-de-feira-de-negocios': typeof FotografoDeFeiraDeNegociosRoute
  '/fotografo-empresarial': typeof FotografoEmpresarialRoute
  '/fotos-corporativas': typeof FotosCorporativasRoute
  '/fotos-profissionais-medicos': typeof FotosProfissionaisMedicosRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/quem-e-o-ale': typeof QuemEOAleRoute
  '/servicos': typeof ServicosRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/video-de-eventos-corporativos': typeof VideoDeEventosCorporativosRoute
  '/video-institucional': typeof VideoInstitucionalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/fotografo-corporativo-em/$bairro': typeof FotografoCorporativoEmBairroRoute
  '/fotografo-corporativo/$slug': typeof FotografoCorporativoSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/fotografo-corporativo-em': typeof FotografoCorporativoEmIndexRoute
  '/fotografo-corporativo': typeof FotografoCorporativoIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/videos': typeof VideosIndexRoute
  '/admin/desempenho': typeof AuthenticatedAdminDesempenhoRoute
  '/admin/indexacao': typeof AuthenticatedAdminIndexacaoRoute
  '/admin/monitoramento': typeof AuthenticatedAdminMonitoramentoRoute
  '/api/public/cron-indexing': typeof ApiPublicCronIndexingRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/staticmap': typeof ApiPublicStaticmapRoute
  '/fotografo-corporativo/categoria/$slug': typeof FotografoCorporativoCategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/busca': typeof BuscaRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/eventos-corporativos': typeof EventosCorporativosRoute
  '/faq': typeof FaqRoute
  '/foto-profissional': typeof FotoProfissionalRoute
  '/foto-profissional-para-linkedin': typeof FotoProfissionalParaLinkedinRoute
  '/fotografia-executiva': typeof FotografiaExecutivaRoute
  '/fotografia-para-advogados': typeof FotografiaParaAdvogadosRoute
  '/fotografia-para-clinicas': typeof FotografiaParaClinicasRoute
  '/fotografo-de-feira-de-negocios': typeof FotografoDeFeiraDeNegociosRoute
  '/fotografo-empresarial': typeof FotografoEmpresarialRoute
  '/fotos-corporativas': typeof FotosCorporativasRoute
  '/fotos-profissionais-medicos': typeof FotosProfissionaisMedicosRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/quem-e-o-ale': typeof QuemEOAleRoute
  '/servicos': typeof ServicosRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/video-de-eventos-corporativos': typeof VideoDeEventosCorporativosRoute
  '/video-institucional': typeof VideoInstitucionalRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/fotografo-corporativo-em/$bairro': typeof FotografoCorporativoEmBairroRoute
  '/fotografo-corporativo/$slug': typeof FotografoCorporativoSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/fotografo-corporativo-em/': typeof FotografoCorporativoEmIndexRoute
  '/fotografo-corporativo/': typeof FotografoCorporativoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/_authenticated/admin/desempenho': typeof AuthenticatedAdminDesempenhoRoute
  '/_authenticated/admin/indexacao': typeof AuthenticatedAdminIndexacaoRoute
  '/_authenticated/admin/monitoramento': typeof AuthenticatedAdminMonitoramentoRoute
  '/api/public/cron-indexing': typeof ApiPublicCronIndexingRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/staticmap': typeof ApiPublicStaticmapRoute
  '/fotografo-corporativo/categoria/$slug': typeof FotografoCorporativoCategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/contato'
    | '/depoimentos'
    | '/eventos-corporativos'
    | '/faq'
    | '/foto-profissional'
    | '/foto-profissional-para-linkedin'
    | '/fotografia-executiva'
    | '/fotografia-para-advogados'
    | '/fotografia-para-clinicas'
    | '/fotografo-de-feira-de-negocios'
    | '/fotografo-empresarial'
    | '/fotos-corporativas'
    | '/fotos-profissionais-medicos'
    | '/llms.txt'
    | '/quem-e-o-ale'
    | '/servicos'
    | '/sitemap-index.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/video-de-eventos-corporativos'
    | '/video-institucional'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/fotografo-corporativo-em/$bairro'
    | '/fotografo-corporativo/$slug'
    | '/portfolio/$slug'
    | '/videos/$slug'
    | '/blog/'
    | '/fotografo-corporativo-em/'
    | '/fotografo-corporativo/'
    | '/portfolio/'
    | '/videos/'
    | '/admin/desempenho'
    | '/admin/indexacao'
    | '/admin/monitoramento'
    | '/api/public/cron-indexing'
    | '/api/public/img'
    | '/api/public/staticmap'
    | '/fotografo-corporativo/categoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/contato'
    | '/depoimentos'
    | '/eventos-corporativos'
    | '/faq'
    | '/foto-profissional'
    | '/foto-profissional-para-linkedin'
    | '/fotografia-executiva'
    | '/fotografia-para-advogados'
    | '/fotografia-para-clinicas'
    | '/fotografo-de-feira-de-negocios'
    | '/fotografo-empresarial'
    | '/fotos-corporativas'
    | '/fotos-profissionais-medicos'
    | '/llms.txt'
    | '/quem-e-o-ale'
    | '/servicos'
    | '/sitemap-index.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/video-de-eventos-corporativos'
    | '/video-institucional'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/fotografo-corporativo-em/$bairro'
    | '/fotografo-corporativo/$slug'
    | '/portfolio/$slug'
    | '/videos/$slug'
    | '/blog'
    | '/fotografo-corporativo-em'
    | '/fotografo-corporativo'
    | '/portfolio'
    | '/videos'
    | '/admin/desempenho'
    | '/admin/indexacao'
    | '/admin/monitoramento'
    | '/api/public/cron-indexing'
    | '/api/public/img'
    | '/api/public/staticmap'
    | '/fotografo-corporativo/categoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/busca'
    | '/contato'
    | '/depoimentos'
    | '/eventos-corporativos'
    | '/faq'
    | '/foto-profissional'
    | '/foto-profissional-para-linkedin'
    | '/fotografia-executiva'
    | '/fotografia-para-advogados'
    | '/fotografia-para-clinicas'
    | '/fotografo-de-feira-de-negocios'
    | '/fotografo-empresarial'
    | '/fotos-corporativas'
    | '/fotos-profissionais-medicos'
    | '/llms.txt'
    | '/quem-e-o-ale'
    | '/servicos'
    | '/sitemap-index.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/video-de-eventos-corporativos'
    | '/video-institucional'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/fotografo-corporativo-em/$bairro'
    | '/fotografo-corporativo/$slug'
    | '/portfolio/$slug'
    | '/videos/$slug'
    | '/blog/'
    | '/fotografo-corporativo-em/'
    | '/fotografo-corporativo/'
    | '/portfolio/'
    | '/videos/'
    | '/_authenticated/admin/desempenho'
    | '/_authenticated/admin/indexacao'
    | '/_authenticated/admin/monitoramento'
    | '/api/public/cron-indexing'
    | '/api/public/img'
    | '/api/public/staticmap'
    | '/fotografo-corporativo/categoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BuscaRoute: typeof BuscaRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  EventosCorporativosRoute: typeof EventosCorporativosRoute
  FaqRoute: typeof FaqRoute
  FotoProfissionalRoute: typeof FotoProfissionalRoute
  FotoProfissionalParaLinkedinRoute: typeof FotoProfissionalParaLinkedinRoute
  FotografiaExecutivaRoute: typeof FotografiaExecutivaRoute
  FotografiaParaAdvogadosRoute: typeof FotografiaParaAdvogadosRoute
  FotografiaParaClinicasRoute: typeof FotografiaParaClinicasRoute
  FotografoDeFeiraDeNegociosRoute: typeof FotografoDeFeiraDeNegociosRoute
  FotografoEmpresarialRoute: typeof FotografoEmpresarialRoute
  FotosCorporativasRoute: typeof FotosCorporativasRoute
  FotosProfissionaisMedicosRoute: typeof FotosProfissionaisMedicosRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  QuemEOAleRoute: typeof QuemEOAleRoute
  ServicosRoute: typeof ServicosRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapVideosDotxmlRoute: typeof SitemapVideosDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  VideoDeEventosCorporativosRoute: typeof VideoDeEventosCorporativosRoute
  VideoInstitucionalRoute: typeof VideoInstitucionalRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  FotografoCorporativoEmBairroRoute: typeof FotografoCorporativoEmBairroRoute
  FotografoCorporativoSlugRoute: typeof FotografoCorporativoSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FotografoCorporativoEmIndexRoute: typeof FotografoCorporativoEmIndexRoute
  FotografoCorporativoIndexRoute: typeof FotografoCorporativoIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  ApiPublicCronIndexingRoute: typeof ApiPublicCronIndexingRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
  ApiPublicStaticmapRoute: typeof ApiPublicStaticmapRoute
  FotografoCorporativoCategoriaSlugRoute: typeof FotografoCorporativoCategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos-corporativos': {
      id: '/eventos-corporativos'
      path: '/eventos-corporativos'
      fullPath: '/eventos-corporativos'
      preLoaderRoute: typeof EventosCorporativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-profissional': {
      id: '/foto-profissional'
      path: '/foto-profissional'
      fullPath: '/foto-profissional'
      preLoaderRoute: typeof FotoProfissionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-profissional-para-linkedin': {
      id: '/foto-profissional-para-linkedin'
      path: '/foto-profissional-para-linkedin'
      fullPath: '/foto-profissional-para-linkedin'
      preLoaderRoute: typeof FotoProfissionalParaLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografia-executiva': {
      id: '/fotografia-executiva'
      path: '/fotografia-executiva'
      fullPath: '/fotografia-executiva'
      preLoaderRoute: typeof FotografiaExecutivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografia-para-advogados': {
      id: '/fotografia-para-advogados'
      path: '/fotografia-para-advogados'
      fullPath: '/fotografia-para-advogados'
      preLoaderRoute: typeof FotografiaParaAdvogadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografia-para-clinicas': {
      id: '/fotografia-para-clinicas'
      path: '/fotografia-para-clinicas'
      fullPath: '/fotografia-para-clinicas'
      preLoaderRoute: typeof FotografiaParaClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-de-feira-de-negocios': {
      id: '/fotografo-de-feira-de-negocios'
      path: '/fotografo-de-feira-de-negocios'
      fullPath: '/fotografo-de-feira-de-negocios'
      preLoaderRoute: typeof FotografoDeFeiraDeNegociosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-empresarial': {
      id: '/fotografo-empresarial'
      path: '/fotografo-empresarial'
      fullPath: '/fotografo-empresarial'
      preLoaderRoute: typeof FotografoEmpresarialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos-corporativas': {
      id: '/fotos-corporativas'
      path: '/fotos-corporativas'
      fullPath: '/fotos-corporativas'
      preLoaderRoute: typeof FotosCorporativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos-profissionais-medicos': {
      id: '/fotos-profissionais-medicos'
      path: '/fotos-profissionais-medicos'
      fullPath: '/fotos-profissionais-medicos'
      preLoaderRoute: typeof FotosProfissionaisMedicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-e-o-ale': {
      id: '/quem-e-o-ale'
      path: '/quem-e-o-ale'
      fullPath: '/quem-e-o-ale'
      preLoaderRoute: typeof QuemEOAleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-videos.xml': {
      id: '/sitemap-videos.xml'
      path: '/sitemap-videos.xml'
      fullPath: '/sitemap-videos.xml'
      preLoaderRoute: typeof SitemapVideosDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-de-eventos-corporativos': {
      id: '/video-de-eventos-corporativos'
      path: '/video-de-eventos-corporativos'
      fullPath: '/video-de-eventos-corporativos'
      preLoaderRoute: typeof VideoDeEventosCorporativosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-institucional': {
      id: '/video-institucional'
      path: '/video-institucional'
      fullPath: '/video-institucional'
      preLoaderRoute: typeof VideoInstitucionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo-em/': {
      id: '/fotografo-corporativo-em/'
      path: '/fotografo-corporativo-em'
      fullPath: '/fotografo-corporativo-em/'
      preLoaderRoute: typeof FotografoCorporativoEmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo-em/$bairro': {
      id: '/fotografo-corporativo-em/$bairro'
      path: '/fotografo-corporativo-em/$bairro'
      fullPath: '/fotografo-corporativo-em/$bairro'
      preLoaderRoute: typeof FotografoCorporativoEmBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo/': {
      id: '/fotografo-corporativo/'
      path: '/fotografo-corporativo'
      fullPath: '/fotografo-corporativo/'
      preLoaderRoute: typeof FotografoCorporativoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo/$slug': {
      id: '/fotografo-corporativo/$slug'
      path: '/fotografo-corporativo/$slug'
      fullPath: '/fotografo-corporativo/$slug'
      preLoaderRoute: typeof FotografoCorporativoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/desempenho': {
      id: '/_authenticated/admin/desempenho'
      path: '/admin/desempenho'
      fullPath: '/admin/desempenho'
      preLoaderRoute: typeof AuthenticatedAdminDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/indexacao': {
      id: '/_authenticated/admin/indexacao'
      path: '/admin/indexacao'
      fullPath: '/admin/indexacao'
      preLoaderRoute: typeof AuthenticatedAdminIndexacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/monitoramento': {
      id: '/_authenticated/admin/monitoramento'
      path: '/admin/monitoramento'
      fullPath: '/admin/monitoramento'
      preLoaderRoute: typeof AuthenticatedAdminMonitoramentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron-indexing': {
      id: '/api/public/cron-indexing'
      path: '/api/public/cron-indexing'
      fullPath: '/api/public/cron-indexing'
      preLoaderRoute: typeof ApiPublicCronIndexingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/staticmap': {
      id: '/api/public/staticmap'
      path: '/api/public/staticmap'
      fullPath: '/api/public/staticmap'
      preLoaderRoute: typeof ApiPublicStaticmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo/categoria/$slug': {
      id: '/fotografo-corporativo/categoria/$slug'
      path: '/fotografo-corporativo/categoria/$slug'
      fullPath: '/fotografo-corporativo/categoria/$slug'
      preLoaderRoute: typeof FotografoCorporativoCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDesempenhoRoute: typeof AuthenticatedAdminDesempenhoRoute
  AuthenticatedAdminIndexacaoRoute: typeof AuthenticatedAdminIndexacaoRoute
  AuthenticatedAdminMonitoramentoRoute: typeof AuthenticatedAdminMonitoramentoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDesempenhoRoute: AuthenticatedAdminDesempenhoRoute,
  AuthenticatedAdminIndexacaoRoute: AuthenticatedAdminIndexacaoRoute,
  AuthenticatedAdminMonitoramentoRoute: AuthenticatedAdminMonitoramentoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BuscaRoute: BuscaRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  EventosCorporativosRoute: EventosCorporativosRoute,
  FaqRoute: FaqRoute,
  FotoProfissionalRoute: FotoProfissionalRoute,
  FotoProfissionalParaLinkedinRoute: FotoProfissionalParaLinkedinRoute,
  FotografiaExecutivaRoute: FotografiaExecutivaRoute,
  FotografiaParaAdvogadosRoute: FotografiaParaAdvogadosRoute,
  FotografiaParaClinicasRoute: FotografiaParaClinicasRoute,
  FotografoDeFeiraDeNegociosRoute: FotografoDeFeiraDeNegociosRoute,
  FotografoEmpresarialRoute: FotografoEmpresarialRoute,
  FotosCorporativasRoute: FotosCorporativasRoute,
  FotosProfissionaisMedicosRoute: FotosProfissionaisMedicosRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  QuemEOAleRoute: QuemEOAleRoute,
  ServicosRoute: ServicosRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapVideosDotxmlRoute: SitemapVideosDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  VideoDeEventosCorporativosRoute: VideoDeEventosCorporativosRoute,
  VideoInstitucionalRoute: VideoInstitucionalRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  FotografoCorporativoEmBairroRoute: FotografoCorporativoEmBairroRoute,
  FotografoCorporativoSlugRoute: FotografoCorporativoSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  FotografoCorporativoEmIndexRoute: FotografoCorporativoEmIndexRoute,
  FotografoCorporativoIndexRoute: FotografoCorporativoIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  ApiPublicCronIndexingRoute: ApiPublicCronIndexingRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
  ApiPublicStaticmapRoute: ApiPublicStaticmapRoute,
  FotografoCorporativoCategoriaSlugRoute:
    FotografoCorporativoCategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
