/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DepoimentosRouteImport } from './routes/depoimentos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FotoProfissionalParaLinkedinRouteImport } from './routes/foto-profissional-para-linkedin'
import { Route as FotografiaParaClinicasRouteImport } from './routes/fotografia-para-clinicas'
import { Route as FotosCorporativasRouteImport } from './routes/fotos-corporativas'
import { Route as QuemEOAleRouteImport } from './routes/quem-e-o-ale'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap-index[.]xml'
import { Route as SitemapVideosDotxmlRouteImport } from './routes/sitemap-videos[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BlogRssDotxmlRouteImport } from './routes/blog.rss[.]xml'
import { Route as FotografoCorporativoEmBairroRouteImport } from './routes/fotografo-corporativo-em.$bairro'
import { Route as FotografoCorporativoIndexRouteImport } from './routes/fotografo-corporativo.index'
import { Route as FotografoCorporativoSlugRouteImport } from './routes/fotografo-corporativo.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'
import { Route as VideosIndexRouteImport } from './routes/videos.index'
import { Route as VideosSlugRouteImport } from './routes/videos.$slug'
import { Route as AuthenticatedAdminIndexacaoRouteImport } from './routes/_authenticated/admin.indexacao'
import { Route as ApiPublicStaticmapRouteImport } from './routes/api/public/staticmap'
import { Route as FotografoCorporativoCategoriaSlugRouteImport } from './routes/fotografo-corporativo.categoria.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DepoimentosRoute = DepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FotoProfissionalParaLinkedinRoute =
  FotoProfissionalParaLinkedinRouteImport.update({
    id: '/foto-profissional-para-linkedin',
    path: '/foto-profissional-para-linkedin',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografiaParaClinicasRoute = FotografiaParaClinicasRouteImport.update({
  id: '/fotografia-para-clinicas',
  path: '/fotografia-para-clinicas',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosCorporativasRoute = FotosCorporativasRouteImport.update({
  id: '/fotos-corporativas',
  path: '/fotos-corporativas',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemEOAleRoute = QuemEOAleRouteImport.update({
  id: '/quem-e-o-ale',
  path: '/quem-e-o-ale',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap-index.xml',
  path: '/sitemap-index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapVideosDotxmlRoute = SitemapVideosDotxmlRouteImport.update({
  id: '/sitemap-videos.xml',
  path: '/sitemap-videos.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRssDotxmlRoute = BlogRssDotxmlRouteImport.update({
  id: '/blog/rss.xml',
  path: '/blog/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografoCorporativoEmBairroRoute =
  FotografoCorporativoEmBairroRouteImport.update({
    id: '/fotografo-corporativo-em/$bairro',
    path: '/fotografo-corporativo-em/$bairro',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografoCorporativoIndexRoute =
  FotografoCorporativoIndexRouteImport.update({
    id: '/fotografo-corporativo/',
    path: '/fotografo-corporativo/',
    getParentRoute: () => rootRouteImport,
  } as any)
const FotografoCorporativoSlugRoute =
  FotografoCorporativoSlugRouteImport.update({
    id: '/fotografo-corporativo/$slug',
    path: '/fotografo-corporativo/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosIndexRoute = VideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosSlugRoute = VideosSlugRouteImport.update({
  id: '/videos/$slug',
  path: '/videos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexacaoRoute =
  AuthenticatedAdminIndexacaoRouteImport.update({
    id: '/admin/indexacao',
    path: '/admin/indexacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicStaticmapRoute = ApiPublicStaticmapRouteImport.update({
  id: '/api/public/staticmap',
  path: '/api/public/staticmap',
  getParentRoute: () => rootRouteImport,
} as any)
const FotografoCorporativoCategoriaSlugRoute =
  FotografoCorporativoCategoriaSlugRouteImport.update({
    id: '/fotografo-corporativo/categoria/$slug',
    path: '/fotografo-corporativo/categoria/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/faq': typeof FaqRoute
  '/foto-profissional-para-linkedin': typeof FotoProfissionalParaLinkedinRoute
  '/fotografia-para-clinicas': typeof FotografiaParaClinicasRoute
  '/fotos-corporativas': typeof FotosCorporativasRoute
  '/quem-e-o-ale': typeof QuemEOAleRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/fotografo-corporativo-em/$bairro': typeof FotografoCorporativoEmBairroRoute
  '/fotografo-corporativo/$slug': typeof FotografoCorporativoSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/fotografo-corporativo/': typeof FotografoCorporativoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/admin/indexacao': typeof AuthenticatedAdminIndexacaoRoute
  '/api/public/staticmap': typeof ApiPublicStaticmapRoute
  '/fotografo-corporativo/categoria/$slug': typeof FotografoCorporativoCategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/faq': typeof FaqRoute
  '/foto-profissional-para-linkedin': typeof FotoProfissionalParaLinkedinRoute
  '/fotografia-para-clinicas': typeof FotografiaParaClinicasRoute
  '/fotos-corporativas': typeof FotosCorporativasRoute
  '/quem-e-o-ale': typeof QuemEOAleRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/fotografo-corporativo-em/$bairro': typeof FotografoCorporativoEmBairroRoute
  '/fotografo-corporativo/$slug': typeof FotografoCorporativoSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/fotografo-corporativo': typeof FotografoCorporativoIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/videos': typeof VideosIndexRoute
  '/admin/indexacao': typeof AuthenticatedAdminIndexacaoRoute
  '/api/public/staticmap': typeof ApiPublicStaticmapRoute
  '/fotografo-corporativo/categoria/$slug': typeof FotografoCorporativoCategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/depoimentos': typeof DepoimentosRoute
  '/faq': typeof FaqRoute
  '/foto-profissional-para-linkedin': typeof FotoProfissionalParaLinkedinRoute
  '/fotografia-para-clinicas': typeof FotografiaParaClinicasRoute
  '/fotos-corporativas': typeof FotosCorporativasRoute
  '/quem-e-o-ale': typeof QuemEOAleRoute
  '/sitemap-index.xml': typeof SitemapIndexDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/rss.xml': typeof BlogRssDotxmlRoute
  '/fotografo-corporativo-em/$bairro': typeof FotografoCorporativoEmBairroRoute
  '/fotografo-corporativo/$slug': typeof FotografoCorporativoSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/videos/$slug': typeof VideosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/fotografo-corporativo/': typeof FotografoCorporativoIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/videos/': typeof VideosIndexRoute
  '/_authenticated/admin/indexacao': typeof AuthenticatedAdminIndexacaoRoute
  '/api/public/staticmap': typeof ApiPublicStaticmapRoute
  '/fotografo-corporativo/categoria/$slug': typeof FotografoCorporativoCategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/depoimentos'
    | '/faq'
    | '/foto-profissional-para-linkedin'
    | '/fotografia-para-clinicas'
    | '/fotos-corporativas'
    | '/quem-e-o-ale'
    | '/sitemap-index.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/fotografo-corporativo-em/$bairro'
    | '/fotografo-corporativo/$slug'
    | '/portfolio/$slug'
    | '/videos/$slug'
    | '/blog/'
    | '/fotografo-corporativo/'
    | '/portfolio/'
    | '/videos/'
    | '/admin/indexacao'
    | '/api/public/staticmap'
    | '/fotografo-corporativo/categoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/depoimentos'
    | '/faq'
    | '/foto-profissional-para-linkedin'
    | '/fotografia-para-clinicas'
    | '/fotos-corporativas'
    | '/quem-e-o-ale'
    | '/sitemap-index.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/fotografo-corporativo-em/$bairro'
    | '/fotografo-corporativo/$slug'
    | '/portfolio/$slug'
    | '/videos/$slug'
    | '/blog'
    | '/fotografo-corporativo'
    | '/portfolio'
    | '/videos'
    | '/admin/indexacao'
    | '/api/public/staticmap'
    | '/fotografo-corporativo/categoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/depoimentos'
    | '/faq'
    | '/foto-profissional-para-linkedin'
    | '/fotografia-para-clinicas'
    | '/fotos-corporativas'
    | '/quem-e-o-ale'
    | '/sitemap-index.xml'
    | '/sitemap-videos.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/blog/$slug'
    | '/blog/rss.xml'
    | '/fotografo-corporativo-em/$bairro'
    | '/fotografo-corporativo/$slug'
    | '/portfolio/$slug'
    | '/videos/$slug'
    | '/blog/'
    | '/fotografo-corporativo/'
    | '/portfolio/'
    | '/videos/'
    | '/_authenticated/admin/indexacao'
    | '/api/public/staticmap'
    | '/fotografo-corporativo/categoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  DepoimentosRoute: typeof DepoimentosRoute
  FaqRoute: typeof FaqRoute
  FotoProfissionalParaLinkedinRoute: typeof FotoProfissionalParaLinkedinRoute
  FotografiaParaClinicasRoute: typeof FotografiaParaClinicasRoute
  FotosCorporativasRoute: typeof FotosCorporativasRoute
  QuemEOAleRoute: typeof QuemEOAleRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
  SitemapVideosDotxmlRoute: typeof SitemapVideosDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogRssDotxmlRoute: typeof BlogRssDotxmlRoute
  FotografoCorporativoEmBairroRoute: typeof FotografoCorporativoEmBairroRoute
  FotografoCorporativoSlugRoute: typeof FotografoCorporativoSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  VideosSlugRoute: typeof VideosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FotografoCorporativoIndexRoute: typeof FotografoCorporativoIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
  VideosIndexRoute: typeof VideosIndexRoute
  ApiPublicStaticmapRoute: typeof ApiPublicStaticmapRoute
  FotografoCorporativoCategoriaSlugRoute: typeof FotografoCorporativoCategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depoimentos': {
      id: '/depoimentos'
      path: '/depoimentos'
      fullPath: '/depoimentos'
      preLoaderRoute: typeof DepoimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foto-profissional-para-linkedin': {
      id: '/foto-profissional-para-linkedin'
      path: '/foto-profissional-para-linkedin'
      fullPath: '/foto-profissional-para-linkedin'
      preLoaderRoute: typeof FotoProfissionalParaLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografia-para-clinicas': {
      id: '/fotografia-para-clinicas'
      path: '/fotografia-para-clinicas'
      fullPath: '/fotografia-para-clinicas'
      preLoaderRoute: typeof FotografiaParaClinicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos-corporativas': {
      id: '/fotos-corporativas'
      path: '/fotos-corporativas'
      fullPath: '/fotos-corporativas'
      preLoaderRoute: typeof FotosCorporativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-e-o-ale': {
      id: '/quem-e-o-ale'
      path: '/quem-e-o-ale'
      fullPath: '/quem-e-o-ale'
      preLoaderRoute: typeof QuemEOAleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-index.xml': {
      id: '/sitemap-index.xml'
      path: '/sitemap-index.xml'
      fullPath: '/sitemap-index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-videos.xml': {
      id: '/sitemap-videos.xml'
      path: '/sitemap-videos.xml'
      fullPath: '/sitemap-videos.xml'
      preLoaderRoute: typeof SitemapVideosDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/rss.xml': {
      id: '/blog/rss.xml'
      path: '/blog/rss.xml'
      fullPath: '/blog/rss.xml'
      preLoaderRoute: typeof BlogRssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo-em/$bairro': {
      id: '/fotografo-corporativo-em/$bairro'
      path: '/fotografo-corporativo-em/$bairro'
      fullPath: '/fotografo-corporativo-em/$bairro'
      preLoaderRoute: typeof FotografoCorporativoEmBairroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo/': {
      id: '/fotografo-corporativo/'
      path: '/fotografo-corporativo'
      fullPath: '/fotografo-corporativo/'
      preLoaderRoute: typeof FotografoCorporativoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo/$slug': {
      id: '/fotografo-corporativo/$slug'
      path: '/fotografo-corporativo/$slug'
      fullPath: '/fotografo-corporativo/$slug'
      preLoaderRoute: typeof FotografoCorporativoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/': {
      id: '/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof VideosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos/$slug': {
      id: '/videos/$slug'
      path: '/videos/$slug'
      fullPath: '/videos/$slug'
      preLoaderRoute: typeof VideosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/indexacao': {
      id: '/_authenticated/admin/indexacao'
      path: '/admin/indexacao'
      fullPath: '/admin/indexacao'
      preLoaderRoute: typeof AuthenticatedAdminIndexacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/staticmap': {
      id: '/api/public/staticmap'
      path: '/api/public/staticmap'
      fullPath: '/api/public/staticmap'
      preLoaderRoute: typeof ApiPublicStaticmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotografo-corporativo/categoria/$slug': {
      id: '/fotografo-corporativo/categoria/$slug'
      path: '/fotografo-corporativo/categoria/$slug'
      fullPath: '/fotografo-corporativo/categoria/$slug'
      preLoaderRoute: typeof FotografoCorporativoCategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminIndexacaoRoute: typeof AuthenticatedAdminIndexacaoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminIndexacaoRoute: AuthenticatedAdminIndexacaoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  DepoimentosRoute: DepoimentosRoute,
  FaqRoute: FaqRoute,
  FotoProfissionalParaLinkedinRoute: FotoProfissionalParaLinkedinRoute,
  FotografiaParaClinicasRoute: FotografiaParaClinicasRoute,
  FotosCorporativasRoute: FotosCorporativasRoute,
  QuemEOAleRoute: QuemEOAleRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
  SitemapVideosDotxmlRoute: SitemapVideosDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogRssDotxmlRoute: BlogRssDotxmlRoute,
  FotografoCorporativoEmBairroRoute: FotografoCorporativoEmBairroRoute,
  FotografoCorporativoSlugRoute: FotografoCorporativoSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  VideosSlugRoute: VideosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  FotografoCorporativoIndexRoute: FotografoCorporativoIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
  VideosIndexRoute: VideosIndexRoute,
  ApiPublicStaticmapRoute: ApiPublicStaticmapRoute,
  FotografoCorporativoCategoriaSlugRoute:
    FotografoCorporativoCategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
